# Generated by Django 5.2.1 on 2025-05-13 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('anciao_do_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes', to=settings.AUTH_USER_MODEL, verbose_name='Ancião do Dia')),
            ],
        ),
        migrations.CreateModel(
            name='ProgDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('momento', models.CharField(max_length=100)),
                ('detalhe', models.CharField(max_length=50)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='ProgSabado.programacao')),
            ],
        ),
    ]
