# Generated by Django 5.2.1 on 2025-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Arquivo de Vídeo')),
                ('publish_date', models.DateField(verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeo Único',
            },
        ),
    ]
