# Generated by Django 5.2.1 on 2025-05-11 08:37

import Boletim.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[Boletim.models.validate_video_file], verbose_name='Arquivo de Vídeo'),
        ),
    ]
