# Generated by Django 5.2.1 on 2025-05-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('momento', models.TextField()),
                ('detalhe', models.TextField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='Home.programacao')),
            ],
        ),
    ]
