# Generated by Django 5.2.1 on 2025-05-13 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='anciao_do_dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes', to=settings.AUTH_USER_MODEL, verbose_name='Ancião do Dia'),
        ),
        migrations.AlterField(
            model_name='progdetail',
            name='detalhe',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='progdetail',
            name='momento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='progdetail',
            name='obs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
