# Generated by Django 5.2.1 on 2025-05-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_programacao_anciao_do_dia_alter_progdetail_detalhe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='anciao_do_dia',
        ),
        migrations.DeleteModel(
            name='ProgDetail',
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
    ]
